spring.application.name=StudentHousing

spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.local.driver-class-name=com.mysql.cj.jdbc.Driver

#Neon cloud config (POSTGRES)
spring.datasource.cloud.url=postgresql://neondb_owner:${CLOUD_PASSWORD}@ep-proud-wind-aqghfodl-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.cloud.username=neondb_owner
spring.datasource.cloud.password=${CLOUD_PASSWORD}
spring.datasource.cloud.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false