# MySQL (Local)
spring.datasource.local.jdbc-url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.local.username=${MYSQL_USERNAME}
spring.datasource.local.password=${MYSQL_PASSWORD}
spring.datasource.local.driver-class-name=com.mysql.cj.jdbc.Driver

# PostgreSQL (Neon Cloud)
spring.datasource.cloud.jdbc-url=jdbc:postgresql://ep-tiny-union-aq5j4iki-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.cloud.username=neondb_owner
spring.datasource.cloud.password=${CLOUD_PASSWORD}
spring.datasource.cloud.driver-class-name=org.postgresql.Driver

# Thymeleaf
spring.thymeleaf.cache=false

# Exclude Spring Boot auto datasource config
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration